name: Reega CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build
      run: ./gradlew shadowJar
    - uses: actions/upload-artifact@v2
      with:
        name: reega.jar
        path: build/libs/reega.jar
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        title: Reega
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: ./build/libs/reega.jar
