name: Reega CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build
      run: ./gradlew shadowJar
    - uses: actions/upload-artifact@v2
      with:
        name: reega.jar
        path: build/libs/reega.jar
        
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        tag: "latest"
        commit: master
        allowUpdates: true
        body: "Reega application"
        artifactErrorsFailBuild: true
        artifacts: ./build/libs/reega.jar
        token: "${{ secrets.GITHUB_TOKEN }}"
